<?php

namespace CustoMood\Bundle\AppBundle\Repository;

/**
 * AdapterMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdapterMetadataRepository extends \Doctrine\ORM\EntityRepository
{
}
