<?php

namespace CustoMood\Bundle\AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find all enabled projects
     * @return array
     */
    public function findAllEnabled()
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->where($qb->expr()->eq('p.enabled', true))
            ->orderBy('p.createdAt', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
