<?php

namespace CustoMood\Bundle\AppBundle\Repository;

/**
 * ProjectSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectSettingRepository extends \Doctrine\ORM\EntityRepository
{

}
