<?php

namespace CustoMood\Bundle\AppBundle\Repository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get ordered settings
     * @return array
     */
    public function findAllOrdered()
    {
        return $this->createQueryBuilder('s')
            ->orderBy('s.settingOrder', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
